version: "3"

services:

  integration_tests:
    build:
      context: ./integration-tests
      dockerfile: Dockerfile.dev
      labels:
        - "com.docker.compose.project=optimism-integration"
        - "com.docker.compose.service=integration_tests"
    volumes:
      - ./:/mnt
    env_file:
      - docker-compose.env
    environment:
      - "REBUILD=${REBUILD}"
      - "FETCH_DEPS=${REBUILD}"

  microservices:
    build:
      context: ./optimism-monorepo
      dockerfile: Dockerfile.dev
      labels:
        - "com.docker.compose.project=optimism-integration"
        - "com.docker.compose.service=microservices"
    volumes:
      - ./:/mnt
    env_file:
      - docker-compose.env
    environment:
      - "REBUILD=${REBUILD}"
      - "FETCH_DEPS=${REBUILD}"

  l1_chain:
    image: trufflesuite/ganache-cli:latest
    entrypoint: node /app/ganache-core.docker.cli.js -p 9545 --gasPrice="0x0" --callGasLimit="0x1fffffffffffff" --gasLimit="0x1fffffffffffff" --account="0xdf8b81d840b9cafc8cd68cf94f093726b174b5f109eba11a3f2a559e5f9e8bce,1000000000000000000000" --account="0x06caa6f48604a58872e27db8c2980584e20faab37613f51383bb5be62db80c50,100000000000000000000" --db /l1-node/l1
    ports:
      - 9545:9545
    volumes:
      - l1-node-data:/l1-node/l1:rw

  postgres:
    build:
      context: ./optimism-monorepo/db
      dockerfile: Dockerfile
      labels:
        - "com.docker.compose.project=optimism-integration"
        - "com.docker.compose.service=postgres"
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - docker-compose.env
    ports:
      - 5432:5432
    environment:
      - "REBUILD=${REBUILD}"

  geth_l2:
    build:
      context: ./go-ethereum
      dockerfile: Dockerfile.dev
      labels:
        - "com.docker.compose.project=optimism-integration"
        - "com.docker.compose.service=geth_l2"
    volumes:
      - ./:/mnt
      - l2-node-data:/l2-node/l2:rw
    env_file:
      - docker-compose.env
    ports:
      - 8545:8545
    environment:
      - "REBUILD=${REBUILD}"

volumes:
  l1-node-data:
  l2-node-data:
  postgres:
