version: "3"

services:

  integration_tests:
    build:
      context: ./integration-tests
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/mnt
    env_file:
      - docker-compose.env

  microservices:
    build:
      context: ./optimism-monorepo
      dockerfile: Dockerfile.dev
    volumes:
      - l1-node-data:/mnt/l1-node:rw
      - l2-node-data:/mnt/l2-node:rw
      - ./optimism-monorepo:/mnt/monorepo
    env_file:
      - docker-compose.env

  l1_chain:
    image: ethereum/client-go:latest
    entrypoint: geth --nousb --dev --http --miner.gasprice 0 --txpool.pricelimit 0 --http.addr '0.0.0.0' --http.port 9545 --ws --ws.addr '0.0.0.0' --ws.port 9545 --http.api='admin,debug,web3,eth,txpool,personal,clique,net' --gcmode=archive --http.vhosts='*' --http.corsdomain='*' --verbosity=6 --dev.period='0'
    ports:
      - 9545:9545

  postgres:
    build:
      context: ./optimism-monorepo/db
      dockerfile: Dockerfile
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - docker-compose.env
    ports:
      - 5432:5432

  geth_l2:
    build:
      context: ./go-ethereum
      dockerfile: Dockerfile.dev
    volumes:
      - l2-node-data:/mnt/l2-node/l2:rw
      - ./:/mnt
    env_file:
      - docker-compose.env
    ports:
      - 8545:8545

volumes:
  l1-node-data:
  l2-node-data:
  postgres:
