version: "3"

services:

  integration_tests:
    image: ethereumoptimism/integration-tests:latest
    volumes:
      - ./integration-tests:/integration-tests
      - ./docker/integration-tests/wait-for-l1-and-l2-and-contract-deployment.sh:/integration-tests/wait.sh
    env_file:
      - docker-compose.env
    environment:
      - "PKGS=integration-tests"

  l1_chain:
    image: ethereumoptimism/hardhat:master
    ports:
      - 9545:9545

  geth_l2:
    image: ethereumoptimism/go-ethereum:latest
    volumes:
      - ./go-ethereum:/go-ethereum
      - ./docker/deployer/wait-for-l1.sh:/bin/wait-for-l1.sh
    env_file:
      - docker-compose.env
    ports:
      - 8545:8545
    working_dir: /go-ethereum
    entrypoint: ["/bin/wait-for-l1.sh", "/go-ethereum/build/bin/geth", "--verbosity=6"]

  batch_submitter:
    image: ethereumoptimism/batch-submitter:master
    env_file:
      - docker-compose.env
    volumes:
     - ./optimism-monorepo:/opt/optimism-monorepo

  deployer:
    image: ethereumoptimism/deployer:master
    env_file:
      - docker-compose.env

volumes:
  geth:
